# Generated by Django 3.0.4 on 2021-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(blank=True, to='main_app.Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='city',
            field=models.ManyToManyField(blank=True, to='main_app.City'),
        ),
    ]
