# Generated by Django 3.0.4 on 2021-04-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210421_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='adverts', to='main_app.Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='adverts', to='main_app.City'),
        ),
    ]
